### PR TITLE
Add SwiftPM support

### PR DESCRIPTION
**Pull request by Kyle-Ye**

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
添加了 SwiftPM 支持，大佬能抽空帮忙看下吗？ @Richard-Cao 

合入后可能还得发布一个新版本才行

**Comment by Richard-Cao** [comment]
@wsxyeah 一起看看

**Comment by wsxyeah** [comment]
这几个头文件是用的软链接？GitHub diff 上看不太出来

**Comment by Kyle-Ye** [comment]
是的，不太想破坏原目录结构，常见的做法是把对应 header 软链到 include 里来满足 Package 要求的 Layout

https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#creating-c-language-targets

```
cd include
ln -s .../**/*.h ./
```

**Comment by wsxyeah** [comment]
> 是的，不太想破坏原目录结构，常见的做法是把对应 header 软链到 include 里来满足 Package 要求的 Layout
> 
> 
> 
> https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#creating-c-language-targets
> 
> 
> 
> ```
> 
> cd include
> 
> ln -s .../**/*.h ./
> 
> ```

配置 `publicHeadersPath` 应该也可以？

**Comment by Kyle-Ye** [comment]
> > 是的，不太想破坏原目录结构，常见的做法是把对应 header 软链到 include 里来满足 Package 要求的 Layout
> > https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#creating-c-language-targets
> > ```
> > 
> > cd include
> > 
> > ln -s .../**/*.h ./
> > ```
> 
> 配置 `publicHeadersPath` 应该也可以？

publicHeadersPath 是额外的for search用的，这里讨论的是 include / modulemap layout

我的经验告诉我是不行的，或者您可以尝试下，直接 comment 提供新的 patch

**Comment by wsxyeah** [comment]
你说的 for search 应该是指 `cSettings.headerSearchPath`？

我看[这个库](https://github.com/SusanDoggie/libjpeg/blob/main/Package.swift)是用的`publicHeadersPath`。

[参考文档](https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html)

**Comment by Kyle-Ye** [comment]
> 你说的 for search 应该是指 `cSettings.headerSearchPath`？
> 
> [参考文档](https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html)

Nope.

Sorry for the miswording/confustion I cause.

You can have a look at the SwiftPM repo code here
```swift
// Compute the path to public headers directory.
let publicHeaderComponent = manifestTarget.publicHeadersPath ?? ClangTarget.defaultPublicHeadersComponent 

public final class ClangTarget: Target {
    /// The default public include directory component.
    public static let defaultPublicHeadersComponent = "include"
```

publicHeadersPath will be "include" if we do not specific it for ClangTarget.

We still need such layout here.

If you do not provide include folder and try set it to "." things will not work here because the layout is not valid.

> 我看[这个库](https://github.com/SusanDoggie/libjpeg/blob/main/Package.swift)是用的`publicHeadersPath`。

If you like, I can add `publicHeadersPath: "include"` here but that's not the point and unnecessary for most of the case.

Again, if you have any better suggestion or comment, I believe the best way is to communicate via code/patch.

**Comment by wsxyeah** [comment]
试了下这样写是可以的
```diff
@@ -38,12 +38,14 @@ let package = Package(
             name: "CLogan",
             dependencies: ["mbedtls"],
             path: "Logan/Clogan",
-            exclude: ["main.c"]
+            exclude: ["main.c"],
+            publicHeadersPath: "./"
         ),
         .target(
             name: "Logan",
             dependencies: ["CLogan"],
-            path: "Logan/iOS"
+            path: "Logan/iOS",
+            publicHeadersPath: "./"
         ),
     ]
 )
```

另外 `.gitignore` 需要添加下 `.build` 目录

**Comment by Kyle-Ye** [comment]
> 试了下这样写是可以的

Thanks, it works. Maybe there is some strange cache issue for my previous try.

> 另外 `.gitignore` 需要添加下 `.build` 目录

Done

**Review by wsxyeah — APPROVED** [review]

**Comment by Richard-Cao** [comment]
@wsxyeah 那我合了？

**Comment by wsxyeah** [comment]
> @wsxyeah 那我合了？

ok

**Comment by wsxyeah** [comment]
> @wsxyeah 那我合了？

ok

**Comment by Richard-Cao** [comment]
> > @wsxyeah 那我合了？
> 
> ok

合了，应该要重新发个版

**Comment by Kyle-Ye** [comment]
> 合了，应该要重新发个版

cc @wsxyeah

**Comment by wsxyeah** [comment]
> > 合了，应该要重新发个版
> 
> 
> 
> cc @wsxyeah 

Done

**Pull request merged**
